<h2>Let's get connected on:</h2><br>

LinkedIn:- https://www.linkedin.com/in/imsiddhant/<br>
Github:- https://github.com/kumarsiddhant1<br>
Facebook:- https://www.facebook.com/siddhant264<br>

## Intro

### Creating Arrays

In [2]:
# Numpy arrays can be created into 2 ways:
    # 1.) From Python list
    # 2.) From In-built NumPy functions
    # 3.) From "Random Functions"

In [1]:
import numpy as np

In [2]:
list1 = [1,2,3,4]
type(list1)

list

In [3]:
array1 = np.array(list1)
print(array1)
print(type(array1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [4]:
list2 = [[1,2,3], [4,5,6], [7,8,9]]
type(list2)

list

In [5]:
matrix = np.array(list2)
print(matrix)
print("\ndimension->", matrix.ndim)
print("\nType->" ,type(matrix) )

[[1 2 3]
 [4 5 6]
 [7 8 9]]

dimension-> 2

Type-> <class 'numpy.ndarray'>


In [6]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [7]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.ones((4,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [9]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [10]:
np.eye(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

#### Randomly Generating

In [21]:
np.random.rand(3,3) #generate random numbers from 0 to 1. Argument->

array([[0.36763013, 0.81678614, 0.97416636],
       [0.22680574, 0.73322781, 0.25173169],
       [0.00236945, 0.73771822, 0.17356346]])

In [22]:
np.random.randn(3,4) #generate random numbers keeping mean zero and standard deviation to 1.

array([[-0.24215604, -0.98676037, -2.03173118, -0.66840002],
       [ 0.48881688, -0.10404865,  0.12955262,  0.18798664],
       [-0.45289703,  0.43687446,  0.83527442,  3.44052664]])

In [47]:
np.random.randint(30,50,3) #generate random numbers from start argument to stop argument given. 3rd argument tells the no of integers we want.

array([43, 49, 48])

In [57]:
np.random.randint(3,10,(3,4))

array([[4, 8, 8, 4],
       [5, 4, 6, 4],
       [6, 8, 3, 7]])

In [92]:
arr = np.arange(10,30)
print(arr)
print("Shape of 1d array->",arr.shape) ##Outputs shape of array 
arr_reshaped = arr.reshape(5,4)
print(arr_reshaped)
print("Shape of reshaped array -> ", arr_reshaped.shape)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
Shape of 1d array-> (20,)
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]
 [26 27 28 29]]
Shape of reshaped array ->  (5, 4)


In [78]:
arr.max()
arr.min()
min(arr)
max(arr)

29

In [81]:
arr.argmax() #Outputs the index of the maximum 
arr.argmin() #Outputs the index of the minimum

0

In [86]:
arr[0].dtype #Outputs data type

dtype('int32')

### Indexing

In [100]:
arr = np.random.randint(15,55,10)
arr

array([26, 48, 51, 34, 19, 32, 49, 18, 23, 24])

In [118]:
print(arr[0:2])
print(arr[0:])
print(arr[:5])
print(arr[3:8])
print(arr[1:1]) #start=stop

[26 48]
[26 48 51 34 19 32 49 18 23 24]
[26 48 51 34 19]
[34 19 32 49 18]
[]


In [117]:
print(arr[1:10:2]) #skipping every 2nd element
print(arr[::-1]) #reversed 
print(arr[0::3])

[48 34 32 18 24]
[24 23 18 49 32 19 34 51 48 26]
[26 34 49 24]


In [159]:
# Multi-Indexing

In [174]:
arr_2d = np.random.randint(10,20,12).reshape(4,3)
print(arr_2d.shape)
arr_2d

(4, 3)


array([[11, 18, 17],
       [11, 12, 15],
       [17, 13, 18],
       [17, 16, 18]])

In [201]:
print(arr_2d[1,1]) #array_name[row index,column index]

print(arr_2d[:,:])

print(arr_2d[0:4,1]) 

print(arr_2d[1:3,1:3]) 

print(arr_2d[0:3:2,1:3]) 

12
[[11 18 17]
 [11 12 15]
 [17 13 18]
 [17 16 18]]
[18 12 13 16]
[[12 15]
 [13 18]]
[[18 17]
 [13 18]]


### Braodcasting

In [148]:
array = np.linspace(1,10,10,dtype=int)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [143]:
# array[0:5] = 100
# array

In [150]:
array_slice = array[0:5] #copy by reference
array_slice

array([1, 2, 3, 4, 5])

In [151]:
array_slice[0:3] = 200

In [152]:
array

array([200, 200, 200,   4,   5,   6,   7,   8,   9,  10])

In [155]:
array_copy = array.copy() 
array_copy

array([200, 200, 200,   4,   5,   6,   7,   8,   9,  10])

In [158]:
array_copy[0:3] = 300
print(array_copy)
print(array)

[300 300 300   4   5   6   7   8   9  10]
[200 200 200   4   5   6   7   8   9  10]


In [206]:
array2 = np.arange(1,11)
array2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [228]:
print(array2[array2 >= 5]) # We can broadcast conditions too. Great filtering method. Isin't it?
print(array2[array2 < 7])
print(array2[array2 == 5])
print(array2[(array2 >= 2) & (array2 <8)]) # Use &(and) and | (or) for multiple condition

[ 5  6  7  8  9 10]
[1 2 3 4 5 6]
[5]
[2 3 4 5 6 7]
