<h2>Let's connecton:</h2><br>

LinkedIn:- https://www.linkedin.com/in/imsiddhant/<br>
Github:- https://github.com/kumarsiddhant1<br>
Facebook:- https://www.facebook.com/siddhant264<br>

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr+arr # We can Add array wit array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [4]:
arr-arr # We can Substract array wit array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
arr+5 # Add any number to array. It will be added to every element of the array.

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [6]:
arr/arr

C:\Users\KIIT\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [7]:
1/arr

C:\Users\KIIT\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [8]:
arr.sum()

55

In [9]:
arr.mean()

5.0

In [10]:
arr.var()

10.0

In [11]:
arr.std()

3.1622776601683795

In [12]:
arr_2d = np.arange(1,21).reshape(5,4)
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [13]:
print(arr_2d.sum()) # Sums all the element
print(arr_2d.sum(axis=0)) # Axis 0 means across rows (Vertically) and Axis 1 means across columns(Horizontally)

210
[45 50 55 60]


In [16]:
arr_2d.shape

(5, 4)

In [17]:
arr_2d.sum(axis=0)

array([45, 50, 55, 60])